version: 2
jobs:
  build:
    docker:
      - image: debian

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Print the size of disk
          command: df
      - run:
          name: Print the files
          command: ls
      
          
         
      
